//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPayment
    {
        public int PaymentID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CardExpire { get; set; }
        public string CVV { get; set; }
        public string CardTitle { get; set; }
        public Nullable<int> StatusID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> BrandID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
