//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public int AddressID { get; set; }
        public string ShortName { get; set; }
        public string Address { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Type { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string PlaceID { get; set; }
        public string LocationAddress { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
