//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCheckout
    {
        public int OrderCheckoutID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public Nullable<double> AmountPaid { get; set; }
        public Nullable<double> AmountTotal { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<double> ServiceCharges { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
