//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public string FullName { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> NumberPerson { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string SittingArea { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ReservationStatus { get; set; }
    }
}
